services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: paititi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    profiles: ["prod"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
