"""change_cip_for_id_in_tests

Revision ID: 019e6b1b01da
Revises: 02cf977f2f6b
Create Date: 2026-03-31 12:33:09.355410

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "019e6b1b01da"
down_revision: str | Sequence[str] | None = "02cf977f2f6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pruebas_metalurgicas", sa.Column("lote_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("pruebas_metalurgicas_cip_fkey"), "pruebas_metalurgicas", type_="foreignkey"
    )
    op.create_foreign_key(None, "pruebas_metalurgicas", "lotes", ["lote_id"], ["id"])
    op.drop_column("pruebas_metalurgicas", "cip")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pruebas_metalurgicas",
        sa.Column("cip", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "pruebas_metalurgicas", type_="foreignkey")
    op.create_foreign_key(
        op.f("pruebas_metalurgicas_cip_fkey"),
        "pruebas_metalurgicas",
        "mapeo_cip",
        ["cip"],
        ["codigo_cip"],
    )
    op.drop_column("pruebas_metalurgicas", "lote_id")
    # ### end Alembic commands ###
