"""add_humedad_minima_to_parametros_comerciales

Revision ID: 021a03faf80b
Revises: aed9d27ddc35
Create Date: 2026-08-12 08:52:37.125247

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "021a03faf80b"
down_revision: str | Sequence[str] | None = "aed9d27ddc35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parametros_comerciales",
        sa.Column("humedad_minima", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.alter_column(
        "pesajes",
        "peso_neto",
        existing_type=sa.NUMERIC(precision=10, scale=3),
        nullable=False,
        existing_server_default=sa.Computed("(peso_inicial - peso_final)", persisted=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pesajes",
        "peso_neto",
        existing_type=sa.NUMERIC(precision=10, scale=3),
        nullable=True,
        existing_server_default=sa.Computed("(peso_inicial - peso_final)", persisted=True),
    )
    op.drop_column("parametros_comerciales", "humedad_minima")
    # ### end Alembic commands ###
