"""Pesajes auditing

Revision ID: 02cf977f2f6b
Revises: 31534ef17722
Create Date: 2026-03-23 10:22:51.446948

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02cf977f2f6b"
down_revision: str | Sequence[str] | None = "31534ef17722"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pesajes", sa.Column("es_manual", sa.Boolean(), nullable=False))
    op.add_column(
        "pesajes", sa.Column("justificacion_manual", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "pesajes",
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column("pesajes", sa.Column("modificado_en", sa.DateTime(), nullable=True))
    op.add_column("pesajes", sa.Column("creado_por", sa.Integer(), nullable=True))
    op.add_column("pesajes", sa.Column("modificado_por", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "pesajes", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "pesajes", "usuarios", ["modificado_por"], ["id"])
    op.drop_index(op.f("ix_sesiones_descarga_offline_id"), table_name="sesiones_descarga")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_sesiones_descarga_offline_id"), "sesiones_descarga", ["offline_id"], unique=True
    )
    op.drop_constraint(None, "pesajes", type_="foreignkey")
    op.drop_constraint(None, "pesajes", type_="foreignkey")
    op.drop_column("pesajes", "modificado_por")
    op.drop_column("pesajes", "creado_por")
    op.drop_column("pesajes", "modificado_en")
    op.drop_column("pesajes", "creado_en")
    op.drop_column("pesajes", "justificacion_manual")
    op.drop_column("pesajes", "es_manual")
    # ### end Alembic commands ###
