"""add cip for prueba

Revision ID: 202546be9351
Revises: 9a29f9a0e5ae
Create Date: 2026-04-15 16:43:39.363371

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202546be9351"
down_revision: str | Sequence[str] | None = "9a29f9a0e5ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pruebas_metalurgicas", sa.Column("cip", sa.String(length=20), nullable=True))
    op.create_foreign_key(None, "pruebas_metalurgicas", "mapeo_cip", ["cip"], ["codigo_cip"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pruebas_metalurgicas", type_="foreignkey")
    op.drop_column("pruebas_metalurgicas", "cip")
    # ### end Alembic commands ###
