"""Balanza_campos

Revision ID: 533090621f00
Revises: 8c90f43e73e8
Create Date: 2026-07-13 13:49:40.348036

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "533090621f00"
down_revision: str | Sequence[str] | None = "8c90f43e73e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "analisis_ley",
        "cip",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_recuperacion",
        "cip",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("pesajes")]
    if "peso_neto" not in columns:
        op.add_column(
            "pesajes",
            sa.Column(
                "peso_neto",
                sa.Numeric(precision=10, scale=2),
                sa.Computed("peso_inicial - peso_final", persisted=True),
                nullable=False,
            ),
        )
    op.alter_column(
        "pruebas_metalurgicas",
        "cip",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pruebas_metalurgicas",
        "cip",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("pesajes")]
    if "peso_neto" in columns:
        op.drop_column("pesajes", "peso_neto")
    op.alter_column(
        "analisis_recuperacion",
        "cip",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_ley",
        "cip",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
