"""change_fk_parametros_comerciales

Revision ID: 77beea852a2c
Revises: 7ee8666ed7a6
Create Date: 2026-02-27 13:02:47.340145

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "77beea852a2c"
down_revision: str | Sequence[str] | None = "7ee8666ed7a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "analisis_detalle",
        "origen",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("analisis_detalle_recuperacion_id_fkey"), "analisis_detalle", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("analisis_detalle_analisis_id_fkey"), "analisis_detalle", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "analisis_detalle", "analisis_recuperacion", ["recuperacion_id"], ["id"]
    )
    op.create_foreign_key(None, "analisis_detalle", "analisis_ley", ["analisis_id"], ["id"])
    op.drop_constraint(op.f("analisis_ley_modificado_por_fkey"), "analisis_ley", type_="foreignkey")
    op.drop_constraint(op.f("analisis_ley_lote_id_fkey"), "analisis_ley", type_="foreignkey")
    op.drop_constraint(op.f("analisis_ley_descartado_por_fkey"), "analisis_ley", type_="foreignkey")
    op.drop_constraint(op.f("analisis_ley_creado_por_fkey"), "analisis_ley", type_="foreignkey")
    op.create_foreign_key(None, "analisis_ley", "usuarios", ["descartado_por"], ["id"])
    op.create_foreign_key(None, "analisis_ley", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "analisis_ley", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "analisis_ley", "lotes", ["lote_id"], ["id"])
    op.drop_constraint(
        op.f("analisis_recuperacion_lote_id_fkey"), "analisis_recuperacion", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("analisis_recuperacion_descartado_por_fkey"),
        "analisis_recuperacion",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("analisis_recuperacion_modificado_por_fkey"),
        "analisis_recuperacion",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("analisis_recuperacion_creado_por_fkey"), "analisis_recuperacion", type_="foreignkey"
    )
    op.create_foreign_key(None, "analisis_recuperacion", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "analisis_recuperacion", "lotes", ["lote_id"], ["id"])
    op.create_foreign_key(None, "analisis_recuperacion", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "analisis_recuperacion", "usuarios", ["descartado_por"], ["id"])
    op.drop_constraint(op.f("campanas_gerencia_id_fkey"), "campanas", type_="foreignkey")
    op.drop_constraint(op.f("campanas_modificado_por_fkey"), "campanas", type_="foreignkey")
    op.drop_constraint(op.f("campanas_creado_por_fkey"), "campanas", type_="foreignkey")
    op.create_foreign_key(None, "campanas", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "campanas", "usuarios", ["gerencia_id"], ["id"])
    op.create_foreign_key(None, "campanas", "usuarios", ["modificado_por"], ["id"])
    op.drop_constraint(
        op.f("configuraciones_modificado_por_fkey"), "configuraciones", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("configuraciones_creado_por_fkey"), "configuraciones", type_="foreignkey"
    )
    op.create_foreign_key(None, "configuraciones", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "configuraciones", "usuarios", ["creado_por"], ["id"])
    op.drop_constraint(op.f("entidades_creado_por_fkey"), "entidades", type_="foreignkey")
    op.drop_constraint(op.f("entidades_modificado_por_fkey"), "entidades", type_="foreignkey")
    op.create_foreign_key(None, "entidades", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "entidades", "usuarios", ["modificado_por"], ["id"])
    op.drop_constraint(
        op.f("entidades_roles_modificado_por_fkey"), "entidades_roles", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("entidades_roles_creado_por_fkey"), "entidades_roles", type_="foreignkey"
    )
    op.create_foreign_key(None, "entidades_roles", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "entidades_roles", "usuarios", ["creado_por"], ["id"])
    op.drop_constraint(op.f("liquidaciones_creado_por_fkey"), "liquidaciones", type_="foreignkey")
    op.drop_constraint(op.f("liquidaciones_cerrado_por_fkey"), "liquidaciones", type_="foreignkey")
    op.drop_constraint(
        op.f("liquidaciones_modificado_por_fkey"), "liquidaciones", type_="foreignkey"
    )
    op.create_foreign_key(None, "liquidaciones", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "liquidaciones", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "liquidaciones", "usuarios", ["cerrado_por"], ["id"])
    op.drop_constraint(
        op.f("liquidaciones_lotes_liquidacion_id_fkey"), "liquidaciones_lotes", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("liquidaciones_lotes_creado_por_fkey"), "liquidaciones_lotes", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("liquidaciones_lotes_modificado_por_fkey"), "liquidaciones_lotes", type_="foreignkey"
    )
    op.create_foreign_key(None, "liquidaciones_lotes", "liquidaciones", ["liquidacion_id"], ["id"])
    op.create_foreign_key(None, "liquidaciones_lotes", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "liquidaciones_lotes", "usuarios", ["modificado_por"], ["id"])
    op.drop_constraint(op.f("lotes_modificado_por_fkey"), "lotes", type_="foreignkey")
    op.drop_constraint(op.f("lotes_estado_modificado_por_fkey"), "lotes", type_="foreignkey")
    op.drop_constraint(op.f("lotes_ruma_id_fkey"), "lotes", type_="foreignkey")
    op.drop_constraint(op.f("lotes_creado_por_fkey"), "lotes", type_="foreignkey")
    op.drop_constraint(op.f("lotes_sesion_id_fkey"), "lotes", type_="foreignkey")
    op.drop_constraint(op.f("lotes_habilitado_por_fkey"), "lotes", type_="foreignkey")
    op.drop_constraint(op.f("lotes_eliminado_por_fkey"), "lotes", type_="foreignkey")
    op.create_foreign_key(None, "lotes", "usuarios", ["habilitado_por"], ["id"])
    op.create_foreign_key(None, "lotes", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "lotes", "sesiones_descarga", ["sesion_id"], ["id"])
    op.create_foreign_key(None, "lotes", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "lotes", "rumas", ["ruma_id"], ["id"])
    op.create_foreign_key(None, "lotes", "usuarios", ["estado_modificado_por"], ["id"])
    op.create_foreign_key(None, "lotes", "usuarios", ["eliminado_por"], ["id"])
    op.drop_constraint(op.f("mapeo_cip_ruma_id_fkey"), "mapeo_cip", type_="foreignkey")
    op.drop_constraint(op.f("mapeo_cip_lote_id_fkey"), "mapeo_cip", type_="foreignkey")
    op.create_foreign_key(None, "mapeo_cip", "rumas", ["ruma_id"], ["id"])
    op.create_foreign_key(None, "mapeo_cip", "lotes", ["lote_id"], ["id"])
    op.drop_constraint(op.f("muestreos_creado_por_fkey"), "muestreos", type_="foreignkey")
    op.drop_constraint(op.f("muestreos_modificado_por_fkey"), "muestreos", type_="foreignkey")
    op.drop_constraint(op.f("muestreos_lote_id_fkey"), "muestreos", type_="foreignkey")
    op.create_foreign_key(None, "muestreos", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "muestreos", "lotes", ["lote_id"], ["id"])
    op.create_foreign_key(None, "muestreos", "usuarios", ["creado_por"], ["id"])
    op.add_column("parametros_comerciales", sa.Column("provacop_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("parametros_comerciales_acopiador_id_key"), "parametros_comerciales", type_="unique"
    )
    op.create_unique_constraint(None, "parametros_comerciales", ["provacop_id"])
    op.drop_constraint(
        op.f("parametros_comerciales_modificado_por_fkey"),
        "parametros_comerciales",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("parametros_comerciales_acopiador_id_fkey"),
        "parametros_comerciales",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("parametros_comerciales_creado_por_fkey"), "parametros_comerciales", type_="foreignkey"
    )
    op.create_foreign_key(None, "parametros_comerciales", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "parametros_comerciales", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(
        None, "parametros_comerciales", "proveedor_acopiador", ["provacop_id"], ["id"]
    )
    op.drop_column("parametros_comerciales", "acopiador_id")
    op.drop_constraint(op.f("permisos_creado_por_fkey"), "permisos", type_="foreignkey")
    op.drop_constraint(op.f("permisos_modificado_por_fkey"), "permisos", type_="foreignkey")
    op.create_foreign_key(None, "permisos", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "permisos", "usuarios", ["modificado_por"], ["id"])
    op.drop_constraint(op.f("pesajes_lote_id_fkey"), "pesajes", type_="foreignkey")
    op.create_foreign_key(None, "pesajes", "lotes", ["lote_id"], ["id"])
    op.drop_constraint(
        op.f("pruebas_metalurgicas_modificado_por_fkey"), "pruebas_metalurgicas", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("pruebas_metalurgicas_creado_por_fkey"), "pruebas_metalurgicas", type_="foreignkey"
    )
    op.create_foreign_key(None, "pruebas_metalurgicas", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "pruebas_metalurgicas", "usuarios", ["creado_por"], ["id"])
    op.drop_constraint(op.f("rumas_modificado_por_fkey"), "rumas", type_="foreignkey")
    op.drop_constraint(op.f("rumas_creado_por_fkey"), "rumas", type_="foreignkey")
    op.create_foreign_key(None, "rumas", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "rumas", "usuarios", ["modificado_por"], ["id"])
    op.drop_constraint(op.f("rumas_campanas_id_campana_fkey"), "rumas_campanas", type_="foreignkey")
    op.drop_constraint(op.f("rumas_campanas_id_ruma_fkey"), "rumas_campanas", type_="foreignkey")
    op.create_foreign_key(None, "rumas_campanas", "rumas", ["id_ruma"], ["id"])
    op.create_foreign_key(None, "rumas_campanas", "campanas", ["id_campana"], ["id"])
    op.drop_constraint(
        op.f("sesiones_descarga_creado_por_fkey"), "sesiones_descarga", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("sesiones_descarga_modificado_por_fkey"), "sesiones_descarga", type_="foreignkey"
    )
    op.create_foreign_key(None, "sesiones_descarga", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "sesiones_descarga", "usuarios", ["creado_por"], ["id"])
    op.drop_constraint(op.f("usuarios_creado_por_fkey"), "usuarios", type_="foreignkey")
    op.drop_constraint(op.f("usuarios_modificado_por_fkey"), "usuarios", type_="foreignkey")
    op.create_foreign_key(None, "usuarios", "usuarios", ["creado_por"], ["id"])
    op.create_foreign_key(None, "usuarios", "usuarios", ["modificado_por"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "usuarios", type_="foreignkey")
    op.drop_constraint(None, "usuarios", type_="foreignkey")
    op.create_foreign_key(
        op.f("usuarios_modificado_por_fkey"),
        "usuarios",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("usuarios_creado_por_fkey"),
        "usuarios",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "sesiones_descarga", type_="foreignkey")
    op.drop_constraint(None, "sesiones_descarga", type_="foreignkey")
    op.create_foreign_key(
        op.f("sesiones_descarga_modificado_por_fkey"),
        "sesiones_descarga",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("sesiones_descarga_creado_por_fkey"),
        "sesiones_descarga",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "rumas_campanas", type_="foreignkey")
    op.drop_constraint(None, "rumas_campanas", type_="foreignkey")
    op.create_foreign_key(
        op.f("rumas_campanas_id_ruma_fkey"),
        "rumas_campanas",
        "rumas",
        ["id_ruma"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("rumas_campanas_id_campana_fkey"),
        "rumas_campanas",
        "campanas",
        ["id_campana"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "rumas", type_="foreignkey")
    op.drop_constraint(None, "rumas", type_="foreignkey")
    op.create_foreign_key(
        op.f("rumas_creado_por_fkey"),
        "rumas",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("rumas_modificado_por_fkey"),
        "rumas",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "pruebas_metalurgicas", type_="foreignkey")
    op.drop_constraint(None, "pruebas_metalurgicas", type_="foreignkey")
    op.create_foreign_key(
        op.f("pruebas_metalurgicas_creado_por_fkey"),
        "pruebas_metalurgicas",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("pruebas_metalurgicas_modificado_por_fkey"),
        "pruebas_metalurgicas",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "pesajes", type_="foreignkey")
    op.create_foreign_key(
        op.f("pesajes_lote_id_fkey"), "pesajes", "lotes", ["lote_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(None, "permisos", type_="foreignkey")
    op.drop_constraint(None, "permisos", type_="foreignkey")
    op.create_foreign_key(
        op.f("permisos_modificado_por_fkey"),
        "permisos",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("permisos_creado_por_fkey"),
        "permisos",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "parametros_comerciales",
        sa.Column("acopiador_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "parametros_comerciales", type_="foreignkey")
    op.drop_constraint(None, "parametros_comerciales", type_="foreignkey")
    op.drop_constraint(None, "parametros_comerciales", type_="foreignkey")
    op.create_foreign_key(
        op.f("parametros_comerciales_creado_por_fkey"),
        "parametros_comerciales",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("parametros_comerciales_acopiador_id_fkey"),
        "parametros_comerciales",
        "entidades",
        ["acopiador_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("parametros_comerciales_modificado_por_fkey"),
        "parametros_comerciales",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "parametros_comerciales", type_="unique")
    op.create_unique_constraint(
        op.f("parametros_comerciales_acopiador_id_key"),
        "parametros_comerciales",
        ["acopiador_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("parametros_comerciales", "provacop_id")
    op.drop_constraint(None, "muestreos", type_="foreignkey")
    op.drop_constraint(None, "muestreos", type_="foreignkey")
    op.drop_constraint(None, "muestreos", type_="foreignkey")
    op.create_foreign_key(
        op.f("muestreos_lote_id_fkey"),
        "muestreos",
        "lotes",
        ["lote_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("muestreos_modificado_por_fkey"),
        "muestreos",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("muestreos_creado_por_fkey"),
        "muestreos",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "mapeo_cip", type_="foreignkey")
    op.drop_constraint(None, "mapeo_cip", type_="foreignkey")
    op.create_foreign_key(
        op.f("mapeo_cip_lote_id_fkey"),
        "mapeo_cip",
        "lotes",
        ["lote_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("mapeo_cip_ruma_id_fkey"),
        "mapeo_cip",
        "rumas",
        ["ruma_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "lotes", type_="foreignkey")
    op.drop_constraint(None, "lotes", type_="foreignkey")
    op.drop_constraint(None, "lotes", type_="foreignkey")
    op.drop_constraint(None, "lotes", type_="foreignkey")
    op.drop_constraint(None, "lotes", type_="foreignkey")
    op.drop_constraint(None, "lotes", type_="foreignkey")
    op.drop_constraint(None, "lotes", type_="foreignkey")
    op.create_foreign_key(
        op.f("lotes_eliminado_por_fkey"),
        "lotes",
        "usuarios",
        ["eliminado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("lotes_habilitado_por_fkey"),
        "lotes",
        "usuarios",
        ["habilitado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("lotes_sesion_id_fkey"),
        "lotes",
        "sesiones_descarga",
        ["sesion_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("lotes_creado_por_fkey"),
        "lotes",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("lotes_ruma_id_fkey"), "lotes", "rumas", ["ruma_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        op.f("lotes_estado_modificado_por_fkey"),
        "lotes",
        "usuarios",
        ["estado_modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("lotes_modificado_por_fkey"),
        "lotes",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "liquidaciones_lotes", type_="foreignkey")
    op.drop_constraint(None, "liquidaciones_lotes", type_="foreignkey")
    op.drop_constraint(None, "liquidaciones_lotes", type_="foreignkey")
    op.create_foreign_key(
        op.f("liquidaciones_lotes_modificado_por_fkey"),
        "liquidaciones_lotes",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("liquidaciones_lotes_creado_por_fkey"),
        "liquidaciones_lotes",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("liquidaciones_lotes_liquidacion_id_fkey"),
        "liquidaciones_lotes",
        "liquidaciones",
        ["liquidacion_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "liquidaciones", type_="foreignkey")
    op.drop_constraint(None, "liquidaciones", type_="foreignkey")
    op.drop_constraint(None, "liquidaciones", type_="foreignkey")
    op.create_foreign_key(
        op.f("liquidaciones_modificado_por_fkey"),
        "liquidaciones",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("liquidaciones_cerrado_por_fkey"),
        "liquidaciones",
        "usuarios",
        ["cerrado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("liquidaciones_creado_por_fkey"),
        "liquidaciones",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "entidades_roles", type_="foreignkey")
    op.drop_constraint(None, "entidades_roles", type_="foreignkey")
    op.create_foreign_key(
        op.f("entidades_roles_creado_por_fkey"),
        "entidades_roles",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("entidades_roles_modificado_por_fkey"),
        "entidades_roles",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "entidades", type_="foreignkey")
    op.drop_constraint(None, "entidades", type_="foreignkey")
    op.create_foreign_key(
        op.f("entidades_modificado_por_fkey"),
        "entidades",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("entidades_creado_por_fkey"),
        "entidades",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "configuraciones", type_="foreignkey")
    op.drop_constraint(None, "configuraciones", type_="foreignkey")
    op.create_foreign_key(
        op.f("configuraciones_creado_por_fkey"),
        "configuraciones",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("configuraciones_modificado_por_fkey"),
        "configuraciones",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "campanas", type_="foreignkey")
    op.drop_constraint(None, "campanas", type_="foreignkey")
    op.drop_constraint(None, "campanas", type_="foreignkey")
    op.create_foreign_key(
        op.f("campanas_creado_por_fkey"),
        "campanas",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("campanas_modificado_por_fkey"),
        "campanas",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("campanas_gerencia_id_fkey"),
        "campanas",
        "usuarios",
        ["gerencia_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "analisis_recuperacion", type_="foreignkey")
    op.drop_constraint(None, "analisis_recuperacion", type_="foreignkey")
    op.drop_constraint(None, "analisis_recuperacion", type_="foreignkey")
    op.drop_constraint(None, "analisis_recuperacion", type_="foreignkey")
    op.create_foreign_key(
        op.f("analisis_recuperacion_creado_por_fkey"),
        "analisis_recuperacion",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("analisis_recuperacion_modificado_por_fkey"),
        "analisis_recuperacion",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("analisis_recuperacion_descartado_por_fkey"),
        "analisis_recuperacion",
        "usuarios",
        ["descartado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("analisis_recuperacion_lote_id_fkey"),
        "analisis_recuperacion",
        "lotes",
        ["lote_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "analisis_ley", type_="foreignkey")
    op.drop_constraint(None, "analisis_ley", type_="foreignkey")
    op.drop_constraint(None, "analisis_ley", type_="foreignkey")
    op.drop_constraint(None, "analisis_ley", type_="foreignkey")
    op.create_foreign_key(
        op.f("analisis_ley_creado_por_fkey"),
        "analisis_ley",
        "usuarios",
        ["creado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("analisis_ley_descartado_por_fkey"),
        "analisis_ley",
        "usuarios",
        ["descartado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("analisis_ley_lote_id_fkey"),
        "analisis_ley",
        "lotes",
        ["lote_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("analisis_ley_modificado_por_fkey"),
        "analisis_ley",
        "usuarios",
        ["modificado_por"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "analisis_detalle", type_="foreignkey")
    op.drop_constraint(None, "analisis_detalle", type_="foreignkey")
    op.create_foreign_key(
        op.f("analisis_detalle_analisis_id_fkey"),
        "analisis_detalle",
        "analisis_ley",
        ["analisis_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("analisis_detalle_recuperacion_id_fkey"),
        "analisis_detalle",
        "analisis_recuperacion",
        ["recuperacion_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "analisis_detalle",
        "origen",
        existing_type=sa.String(length=20),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
