"""add traceability to settlement

Revision ID: 88e8ea610813
Revises: 74dee8a5677c
Create Date: 2026-02-25 15:45:25.267285

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88e8ea610813"
down_revision: str | Sequence[str] | None = "74dee8a5677c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_analisis_ley_lote"), table_name="analisis_ley")
    op.drop_index(op.f("idx_analisis_ley_tipo"), table_name="analisis_ley")
    op.drop_index(op.f("idx_analisis_ley_vigente"), table_name="analisis_ley")
    op.drop_index(op.f("idx_analisis_rec_lote"), table_name="analisis_recuperacion")
    op.drop_index(op.f("idx_analisis_rec_vigente"), table_name="analisis_recuperacion")
    op.drop_index(op.f("idx_campanas_estado"), table_name="campanas")
    op.drop_index(op.f("idx_liquidaciones_estado"), table_name="liquidaciones")
    op.drop_index(op.f("idx_liquidaciones_provacop"), table_name="liquidaciones")
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column("liquidaciones_lotes", sa.Column("modificado_en", sa.DateTime(), nullable=True))
    op.add_column("liquidaciones_lotes", sa.Column("creado_por", sa.Integer(), nullable=True))
    op.add_column("liquidaciones_lotes", sa.Column("modificado_por", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "liquidaciones_lotes", "usuarios", ["modificado_por"], ["id"])
    op.create_foreign_key(None, "liquidaciones_lotes", "usuarios", ["creado_por"], ["id"])
    op.drop_index(op.f("idx_lotes_eliminado"), table_name="lotes")
    op.drop_index(op.f("idx_lotes_estado"), table_name="lotes")
    op.drop_index(op.f("idx_lotes_ip"), table_name="lotes")
    op.drop_index(op.f("idx_lotes_ruma"), table_name="lotes")
    op.drop_index(op.f("idx_lotes_volado"), table_name="lotes")
    op.drop_index(op.f("idx_muestreos_lote"), table_name="muestreos")
    op.drop_index(op.f("idx_params_acopiador"), table_name="parametros_comerciales")
    op.drop_index(op.f("idx_rumas_estado"), table_name="rumas")
    op.drop_index(op.f("idx_sesiones_estado"), table_name="sesiones_descarga")
    op.drop_index(op.f("idx_sesiones_provacop"), table_name="sesiones_descarga")
    op.drop_index(op.f("idx_tokens_expira"), table_name="tokens_revocados")
    op.drop_index(op.f("idx_tokens_jti"), table_name="tokens_revocados")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_tokens_jti"), "tokens_revocados", ["jti"], unique=False)
    op.create_index(op.f("idx_tokens_expira"), "tokens_revocados", ["expira_en"], unique=False)
    op.create_index(
        op.f("idx_sesiones_provacop"), "sesiones_descarga", ["provacop_id"], unique=False
    )
    op.create_index(op.f("idx_sesiones_estado"), "sesiones_descarga", ["estado"], unique=False)
    op.create_index(op.f("idx_rumas_estado"), "rumas", ["estado"], unique=False)
    op.create_index(
        op.f("idx_params_acopiador"), "parametros_comerciales", ["acopiador_id"], unique=False
    )
    op.create_index(op.f("idx_muestreos_lote"), "muestreos", ["lote_id"], unique=False)
    op.create_index(op.f("idx_lotes_volado"), "lotes", ["volado"], unique=False)
    op.create_index(op.f("idx_lotes_ruma"), "lotes", ["ruma_id"], unique=False)
    op.create_index(op.f("idx_lotes_ip"), "lotes", ["ip"], unique=False)
    op.create_index(op.f("idx_lotes_estado"), "lotes", ["estado"], unique=False)
    op.create_index(op.f("idx_lotes_eliminado"), "lotes", ["eliminado"], unique=False)
    op.drop_constraint(None, "liquidaciones_lotes", type_="foreignkey")
    op.drop_constraint(None, "liquidaciones_lotes", type_="foreignkey")
    op.drop_column("liquidaciones_lotes", "modificado_por")
    op.drop_column("liquidaciones_lotes", "creado_por")
    op.drop_column("liquidaciones_lotes", "modificado_en")
    op.drop_column("liquidaciones_lotes", "creado_en")
    op.create_index(
        op.f("idx_liquidaciones_provacop"), "liquidaciones", ["provacop_id"], unique=False
    )
    op.create_index(op.f("idx_liquidaciones_estado"), "liquidaciones", ["estado"], unique=False)
    op.create_index(op.f("idx_campanas_estado"), "campanas", ["estado"], unique=False)
    op.create_index(
        op.f("idx_analisis_rec_vigente"), "analisis_recuperacion", ["vigente"], unique=False
    )
    op.create_index(
        op.f("idx_analisis_rec_lote"), "analisis_recuperacion", ["lote_id"], unique=False
    )
    op.create_index(op.f("idx_analisis_ley_vigente"), "analisis_ley", ["vigente"], unique=False)
    op.create_index(op.f("idx_analisis_ley_tipo"), "analisis_ley", ["tipo_analisis"], unique=False)
    op.create_index(op.f("idx_analisis_ley_lote"), "analisis_ley", ["lote_id"], unique=False)
    # ### end Alembic commands ###
