"""add_ocultar_insumos_and_llampo_params

Revision ID: 8c90f43e73e8
Revises: cdc5b59c624a
Create Date: 2026-07-01 11:31:53.475409

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c90f43e73e8"
down_revision: str | Sequence[str] | None = "cdc5b59c624a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entidades", sa.Column("ocultar_insumos", sa.Boolean(), nullable=True))
    op.add_column(
        "parametros_comerciales",
        sa.Column("gasto_acopio_llampo", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "parametros_comerciales",
        sa.Column("gasto_consumo_llampo", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parametros_comerciales", "gasto_consumo_llampo")
    op.drop_column("parametros_comerciales", "gasto_acopio_llampo")
    op.drop_column("entidades", "ocultar_insumos")
    # ### end Alembic commands ###
