"""change_col_name_to_riesgo_comercial

Revision ID: 91249cbb1ed0
Revises: 77beea852a2c
Create Date: 2026-02-27 15:48:13.364164

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91249cbb1ed0"
down_revision: str | Sequence[str] | None = "77beea852a2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parametros_comerciales",
        sa.Column("riesgo_comercial", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.drop_column("parametros_comerciales", "umbral_recup_alto")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parametros_comerciales",
        sa.Column(
            "umbral_recup_alto",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("parametros_comerciales", "riesgo_comercial")
    # ### end Alembic commands ###
