"""make enter date for pruebas nullable

Revision ID: 9a29f9a0e5ae
Revises: d9d8698ec101
Create Date: 2026-04-15 16:36:45.275549

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a29f9a0e5ae"
down_revision: str | Sequence[str] | None = "d9d8698ec101"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_analisis_rec_estado"), table_name="analisis_recuperacion")
    op.alter_column(
        "pruebas_metalurgicas", "fecha_ingreso", existing_type=sa.DateTime(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pruebas_metalurgicas",
        "fecha_ingreso",
        existing_type=sa.DateTime(),
        nullable=False,
    )
    op.create_index(
        op.f("idx_analisis_rec_estado"), "analisis_recuperacion", ["estado"], unique=False
    )
    # ### end Alembic commands ###
