"""initial structure

Revision ID: 9da9d5c0e40f
Revises:
Create Date: 2026-02-24 10:09:49.134008

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9da9d5c0e40f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codigos",
        sa.Column("grupo", sa.Integer(), nullable=False),
        sa.Column("item", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("descripcion", sa.String(length=100), nullable=True),
        sa.Column("campo1", sa.String(length=200), nullable=True),
        sa.Column("campo2", sa.String(length=200), nullable=True),
        sa.Column("campo3", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("grupo", "item"),
    )
    op.create_table(
        "modulos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=30), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "operaciones",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nombre_completo", sa.String(length=200), nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "campanas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=50), nullable=False),
        sa.Column("meta_oro_fino", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_cierre", sa.Date(), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=True),
        sa.Column("oro_fino_acumulado", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("total_lotes", sa.Integer(), nullable=True),
        sa.Column("total_toneladas", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("total_rumas", sa.Integer(), nullable=True),
        sa.Column("gerencia_id", sa.Integer(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gerencia_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
    )
    op.create_table(
        "configuraciones",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("clave", sa.String(length=100), nullable=False),
        sa.Column("valor", sa.String(length=200), nullable=False),
        sa.Column("descripcion", sa.String(length=200), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clave"),
    )
    op.create_table(
        "entidades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ruc", sa.String(length=11), nullable=False),
        sa.Column("razon_social", sa.String(length=200), nullable=False),
        sa.Column("referencia", sa.Text(), nullable=True),
        sa.Column("tipo", sa.String(length=30), nullable=False),
        sa.Column("direccion", sa.Text(), nullable=True),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ruc"),
    )
    op.create_table(
        "lotes_eliminados",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ip", sa.String(length=20), nullable=False),
        sa.Column("eliminado_por", sa.Integer(), nullable=False),
        sa.Column(
            "fecha_eliminacion", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.Column("datos_originales", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eliminado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permisos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.Column("modulo_id", sa.Integer(), nullable=False),
        sa.Column("operacion_id", sa.Integer(), nullable=False),
        sa.Column("permitido", sa.Boolean(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modulo_id"],
            ["modulos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operacion_id"],
            ["operaciones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rol_id", "modulo_id", "operacion_id", name="uq_permiso_rol_modulo_op"),
    )
    op.create_table(
        "rumas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("numero_ruma", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("codigo_ant", sa.String(length=20), nullable=True),
        sa.Column(
            "fecha_creacion", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=True
        ),
        sa.Column("estado", sa.String(length=20), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo"),
        sa.UniqueConstraint("codigo_ant"),
    )
    op.create_table(
        "entidades_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entidad_id", sa.Integer(), nullable=False),
        sa.Column("rol_id", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entidad_id"],
            ["entidades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rol_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entidad_id", "rol_id", name="uq_entidad_rol"),
    )
    op.create_table(
        "parametros_comerciales",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("acopiador_id", sa.Integer(), nullable=False),
        sa.Column("umbral_recup_bajo", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("umbral_recup_medio", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("umbral_recup_alto", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("lim_ley_comercial", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("dscto_ley_comercial", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("porcentaje_ley_comercial", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("lim_ley_inferior", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("lim_ley_superior", sa.Numeric(precision=5, scale=3), nullable=True),
        sa.Column("gasto_acopio", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("gasto_consumo", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("maquila", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("comision", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acopiador_id"],
            ["entidades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("acopiador_id"),
    )
    op.create_table(
        "proveedor_acopiador",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("proveedor_id", sa.Integer(), nullable=True),
        sa.Column("acopiador_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["acopiador_id"],
            ["entidades.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["entidades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proveedor_id", "acopiador_id", name="uq_proveedor_acopiador"),
    )
    op.create_table(
        "rumas_campanas",
        sa.Column("id_ruma", sa.Integer(), nullable=False),
        sa.Column("id_campana", sa.Integer(), nullable=False),
        sa.Column("tonelaje", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_campana"],
            ["campanas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_ruma"],
            ["rumas.id"],
        ),
        sa.PrimaryKeyConstraint("id_ruma", "id_campana"),
    )
    op.create_table(
        "liquidaciones",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("numero_liquidacion", sa.String(length=50), nullable=True),
        sa.Column("provacop_id", sa.Integer(), nullable=False),
        sa.Column("precio_oro_usd", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("valor_total_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=True),
        sa.Column("cerrado_por", sa.Integer(), nullable=True),
        sa.Column("fecha_cierre", sa.DateTime(), nullable=True),
        sa.Column("pdf_url", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cerrado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provacop_id"],
            ["proveedor_acopiador.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_liquidacion"),
    )
    op.create_table(
        "sesiones_descarga",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provacop_id", sa.Integer(), nullable=False),
        sa.Column("placa", sa.String(length=10), nullable=False),
        sa.Column("carreta", sa.String(length=10), nullable=True),
        sa.Column("conductor", sa.String(length=200), nullable=True),
        sa.Column("transportista", sa.String(length=200), nullable=True),
        sa.Column("razon_social", sa.String(length=200), nullable=True),
        sa.Column("guia_remision", sa.String(length=50), nullable=True),
        sa.Column("guia_transporte", sa.String(length=50), nullable=True),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provacop_id"],
            ["proveedor_acopiador.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lotes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sesion_id", sa.Integer(), nullable=False),
        sa.Column("ip", sa.String(length=20), nullable=False),
        sa.Column("numero_lote", sa.Integer(), nullable=False),
        sa.Column("tipo_material", sa.String(length=20), nullable=True),
        sa.Column("ruma_id", sa.Integer(), nullable=True),
        sa.Column("estado", sa.String(length=30), nullable=False),
        sa.Column("volado", sa.Boolean(), nullable=True),
        sa.Column("dirimencia", sa.Boolean(), nullable=True),
        sa.Column("habilitado_ruma", sa.Boolean(), nullable=True),
        sa.Column("fecha_habilitacion", sa.DateTime(), nullable=True),
        sa.Column("habilitado_por", sa.Integer(), nullable=True),
        sa.Column("estado_modificado_por", sa.Integer(), nullable=True),
        sa.Column("fecha_modificacion_estado", sa.DateTime(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.Column("eliminado", sa.Boolean(), nullable=False),
        sa.Column("eliminado_en", sa.DateTime(), nullable=True),
        sa.Column("eliminado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["eliminado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["estado_modificado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["habilitado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ruma_id"],
            ["rumas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sesion_id"],
            ["sesiones_descarga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ip"),
        sa.UniqueConstraint("sesion_id", "numero_lote", name="uq_lote_sesion_numero"),
    )
    op.create_table(
        "liquidaciones_lotes",
        sa.Column("liquidacion_id", sa.Integer(), nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("fecha_emision", sa.Date(), nullable=True),
        sa.Column("fecha_recepcion", sa.Date(), nullable=True),
        sa.Column("ley_comercial", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("usa_dirimencia", sa.Boolean(), nullable=True),
        sa.Column("oz_tc_planta", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("oz_tc_comercial", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("oz_tc_minero", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("oz_tc_promedio", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("porcentaje_rec_liquido", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("porcentaje_rec_planta", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("fino_recuperable", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["liquidacion_id"],
            ["liquidaciones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes.id"],
        ),
        sa.PrimaryKeyConstraint("liquidacion_id", "lote_id"),
    )
    op.create_table(
        "mapeo_cip",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("ruma_id", sa.Integer(), nullable=True),
        sa.Column("codigo_cip", sa.String(length=20), nullable=False),
        sa.Column("laboratorio", sa.String(length=50), nullable=True),
        sa.Column("fecha_envio", sa.Date(), nullable=True),
        sa.Column("tipo_muestra", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ruma_id"],
            ["rumas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo_cip"),
    )
    op.create_table(
        "muestreos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("intento", sa.Integer(), nullable=False),
        sa.Column("peso_humedo", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("peso_seco", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column(
            "porcentaje_humedad",
            sa.Numeric(precision=5, scale=2),
            sa.Computed(
                "\n            CASE \n                WHEN peso_humedo = 0 THEN 0\n                ELSE ((peso_humedo - peso_seco) / peso_humedo) * 100\n            END\n            ",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("tms_calculado", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lote_id", "intento", name="uq_muestreo_lote_intento"),
    )
    op.create_table(
        "pesajes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("sacos", sa.Integer(), nullable=True),
        sa.Column("peso_inicial", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("peso_final", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("peso_neto", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("numero_ticket", sa.String(length=50), nullable=True),
        sa.Column("fecha_inicio", sa.DateTime(), nullable=True),
        sa.Column("fecha_fin", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("granel", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero_ticket"),
    )
    op.create_table(
        "analisis_ley",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("cip", sa.String(length=20), nullable=True),
        sa.Column("laboratorio", sa.String(length=50), nullable=False),
        sa.Column("tipo_analisis", sa.String(length=20), nullable=False),
        sa.Column("material", sa.String(length=10), nullable=True),
        sa.Column("ley_fino", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("ley_grueso", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("ley_final", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("ley_gr_tm", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("origen_datos", sa.String(length=20), nullable=True),
        sa.Column("fecha_analisis", sa.Date(), nullable=True),
        sa.Column("certificado_url", sa.Text(), nullable=True),
        sa.Column("vigente", sa.Boolean(), nullable=True),
        sa.Column("descartado_por", sa.Integer(), nullable=True),
        sa.Column("fecha_descarte", sa.DateTime(), nullable=True),
        sa.Column("justificacion_descarte", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cip"],
            ["mapeo_cip.codigo_cip"],
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["descartado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analisis_recuperacion",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lote_id", sa.Integer(), nullable=False),
        sa.Column("cip", sa.String(length=20), nullable=True),
        sa.Column("laboratorio", sa.String(length=50), nullable=False),
        sa.Column("ley_cabeza", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("ley_cola", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("ley_liquido", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column(
            "recuperacion",
            sa.Numeric(precision=5, scale=2),
            sa.Computed("((ley_cabeza - ley_cola) / ley_cabeza) * 100", persisted=True),
            nullable=True,
        ),
        sa.Column("origen_datos", sa.String(length=20), nullable=True),
        sa.Column("fecha_analisis", sa.Date(), nullable=True),
        sa.Column("certificado_url", sa.Text(), nullable=True),
        sa.Column("vigente", sa.Boolean(), nullable=True),
        sa.Column("descartado_por", sa.Integer(), nullable=True),
        sa.Column("fecha_descarte", sa.DateTime(), nullable=True),
        sa.Column("justificacion_descarte", sa.Text(), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cip"],
            ["mapeo_cip.codigo_cip"],
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["descartado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lote_id"],
            ["lotes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pruebas_metalurgicas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cip", sa.String(length=20), nullable=True),
        sa.Column("fecha_ingreso", sa.DateTime(), nullable=False),
        sa.Column("malla_porcentaje", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("porcentaje_nacn", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("ph_inicial", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("ph_final", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("adicion_nacn", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("adicion_naoh", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("gasto_agno3", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("creado_en", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cip"],
            ["mapeo_cip.codigo_cip"],
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analisis_detalle",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analisis_id", sa.Integer(), nullable=True),
        sa.Column("recuperacion_id", sa.Integer(), nullable=True),
        sa.Column("origen", sa.Integer(), nullable=False),
        sa.Column("peso", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("ley", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("numero_ensayo", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analisis_id"],
            ["analisis_ley.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recuperacion_id"],
            ["analisis_recuperacion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analisis_detalle")
    op.drop_table("pruebas_metalurgicas")
    op.drop_table("analisis_recuperacion")
    op.drop_table("analisis_ley")
    op.drop_table("pesajes")
    op.drop_table("muestreos")
    op.drop_table("mapeo_cip")
    op.drop_table("liquidaciones_lotes")
    op.drop_table("lotes")
    op.drop_table("sesiones_descarga")
    op.drop_table("liquidaciones")
    op.drop_table("rumas_campanas")
    op.drop_table("proveedor_acopiador")
    op.drop_table("parametros_comerciales")
    op.drop_table("entidades_roles")
    op.drop_table("rumas")
    op.drop_table("permisos")
    op.drop_table("lotes_eliminados")
    op.drop_table("entidades")
    op.drop_table("configuraciones")
    op.drop_table("campanas")
    op.drop_table("usuarios")
    op.drop_table("roles")
    op.drop_table("operaciones")
    op.drop_table("modulos")
    op.drop_table("codigos")
    # ### end Alembic commands ###
