"""add_sesion_documentos

Revision ID: 9f009acaf520
Revises: dcbc546c8e63
Create Date: 2026-03-03 15:18:09.870711

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f009acaf520"
down_revision: str | Sequence[str] | None = "dcbc546c8e63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sesion_documentos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sesion_id", sa.Integer(), nullable=False),
        sa.Column("tipo_documento", sa.String(length=30), nullable=False),
        sa.Column("nombre_original", sa.String(length=255), nullable=False),
        sa.Column("ruta_archivo", sa.String(length=500), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sesion_id"],
            ["sesiones_descarga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sesion_documentos")
    # ### end Alembic commands ###
