"""add_spot_historico

Revision ID: a887c3ee16c0
Revises: 021a03faf80b
Create Date: 2026-08-24 12:55:12.203325

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a887c3ee16c0"
down_revision: str | Sequence[str] | None = "021a03faf80b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spot_historico",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("precio_au_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("precio_ag_usd", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("fuente", sa.String(length=20), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("modificado_en", sa.DateTime(), nullable=True),
        sa.Column("creado_por", sa.Integer(), nullable=True),
        sa.Column("modificado_por", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modificado_por"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fecha"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spot_historico")
    # ### end Alembic commands ###
