"""empty message

Revision ID: ba569ad13cda
Revises: 2f6d163ec46b
Create Date: 2026-06-01 09:31:11.966631

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba569ad13cda"
down_revision: str | Sequence[str] | None = "2f6d163ec46b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analisis_recuperacion", "ley_cola_ag_gr_tm")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analisis_recuperacion",
        sa.Column(
            "ley_cola_ag_gr_tm",
            sa.NUMERIC(precision=10, scale=4),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
