"""Fix division by zero en recuperacion

Revision ID: cdc5b59c624a
Revises: c3d4e5f6a7b8
Create Date: 2026-06-25 10:33:08.899745

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdc5b59c624a"
down_revision: str | Sequence[str] | None = "c3d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "analisis_ley",
        "lote_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="nullable para análisis de Proceso (sin lote)",
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_ley",
        "cip",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_recuperacion",
        "lote_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="nullable para análisis de Proceso (sin lote)",
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_recuperacion",
        "cip",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_recuperacion",
        "sub_tipo",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="Sub-tipo de reconocimiento: SOLIDOS | SOLUCION | NULL (legacy)",
        existing_nullable=True,
    )
    op.alter_column(
        "mapeo_cip",
        "lote_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="nullable para tipo Proceso (sin lote de origen)",
        existing_nullable=True,
    )
    op.alter_column(
        "mapeo_cip",
        "codigo_cip",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="hasta 50 chars para códigos libres de proceso",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    op.execute("UPDATE analisis_recuperacion SET ley_cabeza = NULL WHERE ley_cabeza = 0;")
    op.execute("ALTER TABLE analisis_recuperacion DROP COLUMN recuperacion;")
    op.execute(
        "ALTER TABLE analisis_recuperacion ADD COLUMN recuperacion NUMERIC(5, 2) GENERATED ALWAYS AS ("
        "CASE "
        "WHEN ley_cabeza IS NOT NULL AND ley_cola IS NOT NULL AND ley_cabeza > 0 "
        "THEN ((ley_cabeza - ley_cola) * 100.0) / NULLIF(ley_cabeza, 0) "
        "ELSE NULL END) STORED"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "mapeo_cip",
        "codigo_cip",
        existing_type=sa.VARCHAR(length=50),
        comment="hasta 50 chars para códigos libres de proceso",
        existing_nullable=False,
    )
    op.alter_column(
        "mapeo_cip",
        "lote_id",
        existing_type=sa.INTEGER(),
        comment="nullable para tipo Proceso (sin lote de origen)",
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_recuperacion",
        "sub_tipo",
        existing_type=sa.VARCHAR(length=10),
        comment="Sub-tipo de reconocimiento: SOLIDOS | SOLUCION | NULL (legacy)",
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_recuperacion",
        "cip",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_recuperacion",
        "lote_id",
        existing_type=sa.INTEGER(),
        comment="nullable para análisis de Proceso (sin lote)",
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_ley",
        "cip",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "analisis_ley",
        "lote_id",
        existing_type=sa.INTEGER(),
        comment="nullable para análisis de Proceso (sin lote)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
    op.execute("ALTER TABLE analisis_recuperacion DROP COLUMN recuperacion;")
    op.execute(
        "ALTER TABLE analisis_recuperacion ADD COLUMN recuperacion NUMERIC(5, 2) GENERATED ALWAYS AS ("
        "CASE "
        "WHEN ley_cabeza IS NOT NULL AND ley_cola IS NOT NULL AND ley_cabeza > 0 "
        "THEN ((ley_cabeza - ley_cola) * 100.0) / ley_cabeza "
        "ELSE NULL END) STORED"
    )
