"""empty message

Revision ID: db93dd08305f
Revises: fec33ff674ae
Create Date: 2026-05-05 12:35:55.260918

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db93dd08305f"
down_revision: str | Sequence[str] | None = "fec33ff674ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("spot_usd_snapshot", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("liquidaciones_lotes", "spot_usd_snapshot")
    # ### end Alembic commands ###
