"""editable_values_liquidacionlote

Revision ID: dcbc546c8e63
Revises: 91249cbb1ed0
Create Date: 2026-02-27 17:33:59.388955

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcbc546c8e63"
down_revision: str | Sequence[str] | None = "91249cbb1ed0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("entidades", "ruc", existing_type=sa.VARCHAR(length=11), nullable=True)
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("gasto_acopio_liquidacion", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "liquidaciones_lotes", sa.Column("bono", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("insumos_liquidacion", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("liquidaciones_lotes", "insumos_liquidacion")
    op.drop_column("liquidaciones_lotes", "bono")
    op.drop_column("liquidaciones_lotes", "gasto_acopio_liquidacion")
    op.alter_column("entidades", "ruc", existing_type=sa.VARCHAR(length=11), nullable=False)
    # ### end Alembic commands ###
