"""empty message

Revision ID: fec33ff674ae
Revises: 35bda083c99c
Create Date: 2026-04-29 10:06:19.854643

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fec33ff674ae"
down_revision: str | Sequence[str] | None = "35bda083c99c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_analisis_ley_eliminado"), table_name="analisis_ley")
    op.drop_index(op.f("idx_analisis_rec_eliminado"), table_name="analisis_recuperacion")
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("tms_snapshot", sa.Numeric(precision=10, scale=3), nullable=True),
    )
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("tmh_snapshot", sa.Numeric(precision=10, scale=3), nullable=True),
    )
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("humedad_snapshot", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column("liquidaciones_lotes", sa.Column("sacos_snapshot", sa.Integer(), nullable=True))
    op.add_column(
        "liquidaciones_lotes", sa.Column("fecha_recepcion_lote", sa.Date(), nullable=True)
    )
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("maquila_aplicada", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("riesgo_aplicado", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("precio_x_tms", sa.Numeric(precision=10, scale=4), nullable=True),
    )
    op.add_column(
        "liquidaciones_lotes",
        sa.Column("total_usd", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("liquidaciones_lotes", "total_usd")
    op.drop_column("liquidaciones_lotes", "precio_x_tms")
    op.drop_column("liquidaciones_lotes", "riesgo_aplicado")
    op.drop_column("liquidaciones_lotes", "maquila_aplicada")
    op.drop_column("liquidaciones_lotes", "fecha_recepcion_lote")
    op.drop_column("liquidaciones_lotes", "sacos_snapshot")
    op.drop_column("liquidaciones_lotes", "humedad_snapshot")
    op.drop_column("liquidaciones_lotes", "tmh_snapshot")
    op.drop_column("liquidaciones_lotes", "tms_snapshot")
    op.create_index(
        op.f("idx_analisis_rec_eliminado"), "analisis_recuperacion", ["eliminado"], unique=False
    )
    op.create_index(op.f("idx_analisis_ley_eliminado"), "analisis_ley", ["eliminado"], unique=False)
    # ### end Alembic commands ###
